### ISSUE TITLE
sphinx.conf.example

### ISSUE THREAD

**Issue by korhov** [fheyer/sphinxsearch#7]
You can not use sphinx_catalogsearch_fulltext and do the following:

source magento_fulltext {

...

    sql_query_pre   = SELECT @store_id:=0
    sql_query_pre   = SELECT @catalog_product_id:=entity_type_id FROM eav_entity_type WHERE entity_type_code = 'catalog_product'

    sql_query_pre   = SELECT @description_id:=attribute_id  FROM eav_attribute WHERE entity_type_id = @catalog_product_id AND attribute_code = 'description'
    sql_query_pre   = SELECT @meta_keyword_id:=attribute_id FROM eav_attribute WHERE entity_type_id = @catalog_product_id AND attribute_code = 'meta_keyword'
    sql_query_pre   = SELECT @meta_title_id:=attribute_id   FROM eav_attribute WHERE entity_type_id = @catalog_product_id AND attribute_code = 'meta_title'

	sql_query		= \
		SELECT f1.entity_id, f1.sku, f1.name, v1.value AS description, f1.short_description, v2.value AS meta_keyword, v3.value AS meta_title, \
		       GROUP_CONCAT(DISTINCT c1.name ORDER BY c1.name SEPARATOR ',') category \
        FROM catalog_product_flat_1 f1 \
        LEFT JOIN catalog_category_product cp ON cp.product_id = f1.entity_id \
        LEFT JOIN catalog_category_flat_store_1 c1 ON c1.entity_id = cp.category_id \
        LEFT JOIN catalog_product_entity_text v1    ON v1.entity_id = f1.entity_id AND v1.store_id = @store_id AND v1.attribute_id = @description_id \
        LEFT JOIN catalog_product_entity_text v2    ON v2.entity_id = f1.entity_id AND v2.store_id = @store_id AND v2.attribute_id = @meta_keyword_id \
        LEFT JOIN catalog_product_entity_varchar v3 ON v3.entity_id = f1.entity_id AND v3.store_id = @store_id AND v3.attribute_id = @meta_title_id \
        GROUP BY f1.entity_id

...

}

Thereafter, the code can be deleted.
Disable indexing in Magento. Indexation is using Sphinx.

**Comment by fheyer** [comment]
I wouldn't go this direction.
To improve the sphinxsearch module i would use Magento's own table "catalogsearch_fulltext" as index source. That way we respect all search related settings in Magento (e.g. selection of indexable attributes). Going that way we could eliminate sphinxsearch's own index table.
